name: SSH Server and Restart Docker Compose

on:
    push:
        branches:
            - 'main'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v2
        with:
            ref: main
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }} # Secret 새로 추가 됨
            password: ${{ secrets.DOCKERHUB_TOKEN }} # Secret 새로 추가 됨
    - 
      name: Add envs # Secret 여러개 새로 추가 됨
      run: |
        echo "REACT_APP_KAKAO_JAVASCRIPT_KEY=${{ secrets.REACT_APP_KAKAO_JAVASCRIPT_KEY }}" > ./frontend/.env 
        echo "REACT_APP_KAKAO_REDIRECT_URI=http://localhost:3000/auth/kakao/callback" >> ./frontend/.env
        echo "REACT_APP_API_BASE_URL=http://13.125.119.35:5001/api" >> ./frontend/.env

        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > ./server/.env
        echo "DB_HOST=db" >> ./server/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> ./server/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./server/.env
        echo "DB_NAME=buddy_bee" >> ./server/.env
        echo "DB_DATABASE=buddy_bee" >> ./server/.env
        echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> ./server/.env
        echo "KAKAO_REDIRECT_URI=http://localhost:3000/auth/kakao/callback" >> ./server/.env
        echo "EMAIL_USER=gogo981004@gmail.com" >> ./server/.env
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> ./server/.env
    -
        name: Build Container Image
        uses: docker/build-push-action@v4
        with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/buddy-bee:latest
    - 
        name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}      
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            port: 22
            timeout: 40s  # 30초 기본        
            script: |
                cd Buddy-Bee
                git pull
                docker compose pull web
                docker compose up -d web
