name: Close associated issue

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Close associated issue
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL | jq -r '.body')
          ISSUE_NUMBERS=$(echo $PR_BODY | grep -oiE "(fixes|closes|resolves) #[0-9]+" | grep -oE "#[0-9]+" | tr -d '#')
          if [[ ! -z "$ISSUE_NUMBERS" ]]; then
            for ISSUE_NUMBER in $ISSUE_NUMBERS; do
              echo "Closing issue $ISSUE_NUMBER"
              curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X PATCH "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER" -d '{"state": "closed"}'
            done
          fi
        shell: bash
